### PR TITLE
Remove radial gradient 2x2, clarify PaintTransformed interaction with gradients

### LINKED ISSUE #45: Transform in linear/radial gradient redundant?
Originally we added an `Affine2x2` to linear and radial gradients because necessary. But since we have added an `Affine2x3` now, I believe the `Affine2x2`s can be removed.

### PR DESCRIPTION
**Pull request by rsheeter**
Also remove the special rules for handling that 2x2.

### CODE REVIEW

**Comment by behdad** [comment]
Awesomeness. LGTM. Thanks!

**Comment by rsheeter** [comment]
Per IM, working on expanding this to adjust linear gradient as well.

**Comment by behdad** [comment]
We need the actual points P0 and P1 or variations cannot work correctly.

**Comment by rsheeter** [comment]
I'm going to back out the linear changes and put those in a separate PR then.

**Pull request merged**
