### PR TITLE
16-bit GIDs, remove Point struct, rename transparency -> alpha, and other renames

### PR DESCRIPTION
**Pull request by anthrotype**
This incorporates a few proposed changes that arose from discussions with @PeterConstable in

https://github.com/googlefonts/colr-gradients-spec/issues/14
https://github.com/googlefonts/colr-gradients-spec/issues/17
https://github.com/googlefonts/colr-gradients-spec/issues/18
https://github.com/googlefonts/colr-gradients-spec/issues/19
https://github.com/googlefonts/colr-gradients-spec/issues/21

### CODE REVIEW

**Comment by anthrotype** [comment]
basically this matches https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev3.md (only difference is that GlyphIDs are kept as 32-bit like in the original current draft revision)

**Comment by anthrotype** [comment]
I went on and changed from base glyph and layer glyph IDs from 32-bit to 16-bit unsigned.
@behdad please let us know if you are ok with the change.

**Comment by behdad** [comment]
lgtm.

**Comment by PeterConstable** [comment]
@anthrotype : Can you point me at an updated version of noto-handwriting-color_1.ttf that reflects these changes, and a COlR dump if that's available?

**Comment by anthrotype** [comment]
it's at https://github.com/googlefonts/color-fonts/blob/master/fonts/noto-emoji-glyf_colr_1.ttf

by COLR dump you mean the .ttx file for the COLR table only? here is the dump for the full font file. 
[noto-emoji-glyf_colr_1.zip](https://github.com/googlefonts/colr-gradients-spec/files/5064828/noto-emoji-glyf_colr_1.zip)

you can generate one by running the ttx command on the TTF file with the latest fonttools.

**Comment by anthrotype** [comment]
ah you said `noto-handwriting` only. It's in the same repository.
https://github.com/googlefonts/color-fonts/blob/master/fonts/noto-handwriting-glyf_colr_1.ttf

dumped to ttx here
[noto-handwriting-glyf_colr_1.zip](https://github.com/googlefonts/colr-gradients-spec/files/5064843/noto-handwriting-glyf_colr_1.zip)

**Pull request merged**
