### PR TITLE
Add note to PaintColrGlyph contrasting with PaintColrLayers

### PR DESCRIPTION
**Pull request by PeterConstable**

### CODE REVIEW

**Comment by drott** [comment]
Thanks, LGTM. I took the freedom to line-break the note and add markdown formatting, hope that's okay.

**Review by drott — APPROVED** [review]

**Comment by PeterCon** [comment]
NP. I had "NOTE" formatted the way it would appear in OFF, but that's a minor detail.

**Comment by drott** [comment]
Ok, I realized we have less consistent formatting of the Notes paragraphs than I thought, so we should probably do a pass to harmonize them.

**Comment by PeterCon** [comment]
Your convention is fine.

**Pull request merged**
