### PR TITLE
Add example of first circle contained in second

### LINKED ISSUE #22: provide example of radial gradient with degenerate transform
Radial gradients can contain a 2x2 affine matrix to transform the two circles into ellipses, but _without affecting the position of their centres_ -- unlike SVG's `gradientTransform`, or "graphics systems like Skia or Cairo that apply their (often called user-) transformation matrix to everything".
When rendering CORLv1 radial gradients using the latter graphics systems, one should thus apply the _inverse_ matrix to the centres' coordinates to undo the effect of applying the matrix to everything.
But of course some matrices are singular or degenerate (with 0 determinant) and cannot be inverted.
 
The draft spec notes that even these have a "well defined shape", however it is not clear to me what this shape should look like. A visual example could help a lot here.

This is the relevant paragraph:

> Note: Implementations must be careful to properly render radial gradient even if the provided affine matrix is degenerate or near-degenerate. Such radial gradients do have a well-defined shape, which is a strip or a cone filled with a linear gradient. Implementations using the inverse-transform approach noted above can fall back to a linear-gradient combined with a clipping path to achieve proper rendering of problematic affine transforms.

### PR DESCRIPTION
**Pull request by drott**
Fixes #22.

### CODE REVIEW

**Comment by drott** [comment]
Preview link: https://github.com/drott/colr-gradients-spec/tree/radialContainedExample

**Review by rsheeter — APPROVED** [review]

**Comment by PeterConstable** [comment]
I had already generated svg/png for this, but hadn't yet gotten to creating a PR to add to this repo. It was in the PDF I sent you a few days ago.

**Comment by drott** [comment]
> I had already generated svg/png for this, but hadn't yet gotten to creating a PR to add to this repo. It was in the PDF I sent you a few days ago.

Thanks - it was quickly done so I thought I make those so we can make progress and close some issues. As this PR is ready to merge, do you have a preference which ones to land? I am fine either way as long as we have a separate PR for them.

**Comment by PeterConstable** [comment]
Yours and mind have separate advantages:
- yours has the circles closer to the horizontal center, so more of the extend on the right side is visible.
- in mind, I moved the label for c0 so that less of the extend gradation within the small circle was covered.
I'll rev mind to incorporate the advantage of yours.

**Comment by drott** [comment]
Merged #111 instead.

**Pull request closed without merging**
