### PR TITLE
First draft of PaintGroup (per Behdad proposal on #32)

### LINKED ISSUE #32: Multi-layer opacity
Compiling vector graphic sources, such as svgs, to COLR fonts will be significant to icon and emoji use cases (twemoji, noto emoji, and others come to mind). SVG allows application of opacity to multiple layers at once (by setting opacity on a group), meaning effectively render the group then apply opacity to the end result, as I understand it.

The current COLR spec doesn't allow for this. Building equivalent stacks of individually layers with opacity to match a group of layers with opacity appears tiresome. Also, when I tried to construct equivalent individual layers to a simple group opacity setup (courtesy of @anthrotype) by hand I immediately ran into halo effects (from anti-aliasing?). 

Off the top of my head there are three main options

1. Use some 2D graphics technique I'm unaware of to build equivalent single layers to match the group w/o introducing artifacts. Hooray, there is no actual problem :)
1. Add the ability to designate groups of layers with opacity to COLR
1. Accept that this is not supported by COLR; the set of things we can represent in COLR just got smaller

### PR DESCRIPTION
**Pull request by rsheeter**
Add reuse by group to COLRv1. Once acceptable will circle back to add blend mode.

Fixes #32.

### CODE REVIEW

**Comment by PeterConstable** [comment]
Thanks. It's not clear from the structures what is getting grouped by a format 4 paint. 

```
struct PaintGroup
{
  uint16              format; // = 4
  VarF2DOT14          alpha;
  Offset32<Affine2x3> transform; // May be NULL.
};
```
Did you intend to have something referring to other layers or glyphs? Does it group layers above it up to the next layer using format 4 paint? Or all layers above it?

Also, not sure if you saw my suggestion in #32 : I think it would be super useful to be able to define an opacity mask using a gradient --- similar to putting a BW gradient into an alpha channel or layer mask in Photoshop. Is that something that can be accommodated after circling back to add blend modes?

**Comment by rsheeter** [comment]
> It's not clear from the structures what is getting grouped by a format 4 paint.

The idea is that for a layer with paint format 4 (group) the layer gid is to be interpreted as a reference to another COLR glyph. That glyph has a set of layers; those layers are the ones in the group. So, once you have a multi-layer COLR glyph you can reuse it - transformed - as part of another one.

> I think it would be super useful to be able to define an opacity mask using a gradient

I suggest we consider this along with blend modes.

**Comment by PeterConstable** [comment]
Got it. I was forgetting the LayerV1Record that joins the paint to a gid. (Doh!)

**Comment by rsheeter** [comment]
I added a bit more detail to the group section as I think it would be fair to say it was underspecified.

**Comment by PeterConstable** [comment]
I've rev'd my OT formats draft accordingly: [rev 5](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev5.md)

**Comment by PeterConstable** [comment]
Any concern about burning GIDs?

(I know: would provide more impetus for 32-bit GIDs.)

**Comment by behdad** [comment]
> Any concern about burning GIDs?

This will generally save GIDs because of the transformation possible. But valid point.

> (I know: would provide more impetus for 32-bit GIDs.)

Here's another idea:
1. reinstate 32bit GIDs in COLRv1 table,
2. allow GIDs within this table to go beyond the font's numGlyphs. Then all the group GIDs can use the top range without interference...

I know this is getting into dangerous territory. But this is what I envision a gradual shift to 32bit GIDs will look like. Kinda like how PC moved from 16bit pointers to 32bit by going through "High Memory", "Extended Memory", "Expanded Memory" etc address modes...

**Comment by rsheeter** [comment]
Burning gids isn't any worse because of this. 

> a gradual shift to 32bit GIDs

Perhaps this is naive but ideally I would like to avoid this type of thing and instead attack 32 bit gids head-on as a separate project, hopefully drawing together interested parties from the nascent CG. I imagine that consists of defining a whole bunch of new table versions that support 32 bit gid/offsets.

**Comment by rsheeter** [comment]
Merging per IM confirmation with Behdad this looks OK. If we want to debate 32 bit gids lets re-open #8.

**Pull request merged**
