### PR TITLE
Refine group definition

### PR DESCRIPTION
**Pull request by drott**
Fix reference of LayerV1Glyph to LayerV1Record, add alpha computation
description.

### CODE REVIEW

**Comment by drott** [comment]
@rsheeter @behdad @PeterConstable PTAL.

**Review by PeterConstable — APPROVED** [review]

**Comment by behdad** [comment]
I'm not sure about this:
```
The `alpha` value of the group is multiplied with the `alpha` values of the
individual `ColorIndex` values that are part of the `ColorLine` of the nested
`Paint` structures.
```

The whole point of a group paint is that the group is painted in isolation completely, and the result is alpha-blended with a fixed `alpha`. So the `alpha` and the individual colors never interact directly and no such multiplication happens ever.

**Comment by drott** [comment]
I think I see what you mean. It is painted in isolation, based on ColorLine/ColorStops  including their individual alpha, then composited down to what's been painted so far, based on group alpha. But I agree it's indirect and left to the compositing implementation of the 2D graphics library.  Remove this part, or rephrase it, perhaps as follows:

> The  `alpha` value of the group is used for compositing down after isolated painting of the layers from `BaseGlyphV1Record` has completed.

**Comment by rsheeter** [comment]
The offending section is deleted when we move to DAG (#37) per conversation yesterday so closing for now.

**Pull request closed without merging**
